<?php

declare(strict_types=1);

namespace MunicipioClone\Import;

use WpService\WpService;

/**
 * Rewrites cloned multisite attachment URLs to their source-site media path.
 */
class RemoteMediaUrlRewriter
{
    private const SOURCE_BLOG_ID_OPTION = 'municipio_clone_remote_media_source_blog_id';

    /**
     * @param WpService $wpService WordPress operations for the active site.
     */
    public function __construct(private WpService $wpService)
    {
    }

    /**
     * Stores the source blog ID that should provide attachment URLs for a clone.
     *
     * @param int $targetBlogId The imported target site's blog ID.
     * @param int $sourceBlogId The exported source site's blog ID.
     * @param bool $keepRemoteMediaUrls Whether remote media URLs should be retained.
     */
    public function configure(int $targetBlogId, int $sourceBlogId, bool $keepRemoteMediaUrls): void
    {
        $this->wpService->switchToBlog($targetBlogId);
        try {
            $this->wpService->updateOption(
                self::SOURCE_BLOG_ID_OPTION,
                $keepRemoteMediaUrls ? $sourceBlogId : 0,
            );
        } finally {
            $this->wpService->restoreCurrentBlog();
        }
    }

    /**
     * Replaces the target multisite uploads segment with the source site segment.
     *
     * @param string $url The attachment URL generated by WordPress.
     * @param int $attachmentId The attachment being resolved.
     * @return string The source media URL when configured, otherwise the original URL.
     */
    public function filterAttachmentUrl(string $url, int $attachmentId): string
    {
        $sourceBlogId = (int) $this->wpService->getOption(self::SOURCE_BLOG_ID_OPTION, 0);
        $targetBlogId = $this->wpService->getCurrentBlogId();
        if ($sourceBlogId <= 0 || $sourceBlogId === $targetBlogId) {
            return $url;
        }

        $targetSegment = '/sites/' . $targetBlogId;
        $sourceSegment = '/sites/' . $sourceBlogId;

        return str_replace($targetSegment . '/', $sourceSegment . '/', $url);
    }
}