<?php

declare(strict_types=1);

namespace MunicipioClone\Import;

use WpService\WpService;

/**
 * Rewrites cloned attachment URLs to their source-site media location.
 */
class RemoteMediaUrlRewriter
{
    private const SOURCE_URL_OPTION = 'municipio_clone_remote_media_source_url';

    /**
     * @param WpService $wpService WordPress operations for the active site.
     */
    public function __construct(private WpService $wpService)
    {
    }

    /**
     * Stores the source site's media base URL that should provide attachment URLs for a clone.
     *
     * @param int $targetBlogId The imported target site's blog ID.
     * @param string $sourceMediaBaseUrl The exported source site's effective uploads base URL.
     * @param bool $keepRemoteMediaUrls Whether remote media URLs should be retained.
     */
    public function configure(int $targetBlogId, string $sourceMediaBaseUrl, bool $keepRemoteMediaUrls): void
    {
        $this->wpService->switchToBlog($targetBlogId);
        try {
            $this->wpService->updateOption(
                self::SOURCE_URL_OPTION,
                $keepRemoteMediaUrls ? rtrim($sourceMediaBaseUrl, '/') : '',
            );
        } finally {
            $this->wpService->restoreCurrentBlog();
        }
    }

    /**
     * Replaces the target site's own uploads base URL with the source site's uploads base URL.
     *
     * @param string $url The attachment URL generated by WordPress.
     * @param int $attachmentId The attachment being resolved.
     * @return string The source media URL when configured, otherwise the original URL.
     */
    public function filterAttachmentUrl(string $url, int $attachmentId): string
    {
        $sourceMediaBaseUrl = (string) $this->wpService->getOption(self::SOURCE_URL_OPTION, '');
        if ($sourceMediaBaseUrl === '') {
            return $url;
        }

        $targetMediaBaseUrl = rtrim((string) ($this->wpService->wpGetUploadDir()['baseurl'] ?? ''), '/');
        if ($targetMediaBaseUrl === '' || !str_starts_with($url, $targetMediaBaseUrl . '/')) {
            return $url;
        }

        return $sourceMediaBaseUrl . substr($url, strlen($targetMediaBaseUrl));
    }
}